@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN

title Диаграмма компонентов

Container(VK, "Вконтакте", "VK API", "Публикация сертификата игрока на стене")

Container_Boundary(Game, "Игра") {
    Component(Game, "Game", "C#", "Управляет основной логикой игры")
    Component(CameraSettings, "Camera Settings", "C#", "Управляет поведением камеры")
    Component(PlayerSettings, "Player Settings", "C#", "Управляет поведением персонажа")
    Component(Questions, "Question", "C#", "Управляет вопросами")
    Component(UI, "UI Handler", "C#", "Управляет интерфейсом")
    Component(Field, "Field", "C#", "Задает путь передвидения персонажей")
    Component(Multiplayer, "Multiplayer", "C#", "Управляет запросами к VK")
}

Rel(CameraSettings, Game, "Следит за активным игроком")

Rel(UI, PlayerSettings, "Выполняет события при взаимодействии с интерфейсом")
Rel(UI, Game, "Выполняет события при взаимодействии с интерфейсом")

Rel(Multiplayer, PlayerSettings, "Взаимодействие игроков по сети")
Rel(Multiplayer, Game, "Взаимодействие игроков по сети")

Rel(Game, PlayerSettings, "Переключает активного игрока")

Rel(PlayerSettings, Game, "Переключает активного игрока")
Rel(PlayerSettings, Field, "Получает направление движения")

Rel(Questions, Field, "Определяет тип вопроса")
Rel(Questions, Game, "Отправляет данные вопросов")

Rel(Field, Game, "Переключает активного игрока")
Rel(Field, Questions, "Запрашивает вопрос")
Rel(Field, PlayerSettings, "Запрашивает активного игрока")

@enduml