@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN

title Диаграмма контейнеров

Person(Admin, "Администратор", "Заполняет и редактирует базу данных")
Person(Player, "Игрок", "Использует приложение для получения удовольствия и новых знаний")
Person(Visiter, "Визитер", "Регистрируется в игре")

System_Boundary(c1, "Жизнь бурого мишки") {
    Container(Game, "Игра", "Unity Engine, C# (iOS, Android, PC)", "Пользовательский функционал")
    Container(BackendApi, "Backend API", "C#", "Бизнес логика приложения в виде API")
    ContainerDb(Database, "База данных", "Scriptable object", "Хранилище вопросов игры")
}
Container(VK, "Вконтакте", "VK API", "Публикация сертификата игрока на стене")


Rel(Admin, Database, "Редактирует")
Rel(Player, Game, "Играет", "HTTPS")
Rel(Visiter, Game, "Регистрируется", "HTTPS")

Rel(Game, BackendApi, "Отправка и получение данных от сервера")
Rel(BackendApi, Database, "Чтение из БД")

Rel_Neighbor(Game, VK, "Публикация сертификата")

@enduml